# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ac085e34b0e7027b440912bd3264bee5e51abfa50df2c176fafd4c0b8365e1f5dbaebb988cf67f883725962dbce33e32ecfa936ea5fa12107a4c5b40fbdc76c

test:
  secret_key_base: a5e04b8e5b8b4ced5a25808e9170996491b3a13f7b8dd9bda607a850741282aa53c8a8a47ead4d8b9171e854c22056c53bb09e4181cdf53975e18d6f777aa01e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
